apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mxjobs.qiniu.com
spec:
  group: qiniu.com
  names:
    kind: MXJob
    listKind: MXJobList
    plural: mxjobs
    singular: mxjob
  scope: Namespaced
  version: v1alpha1
